---

# Install ZSH

- name: Installing Shell packages
  pacman:
    state: latest
    name:
      - sakura
      - zsh

- name: Checking Oh-my-ZSH presence
  register: zsh
  stat: path="/home/{{username}}/.oh-my-zsh"

- name: Installing Oh-my-ZSH
  when: zsh.stat.exists == False
  become: yes
  become_user: "{{username}}"
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest="/home/{{username}}/.oh-my-zsh"

- name: Updating Sakura launcher to use Sommelier
  replace:
    dest: /usr/share/applications/sakura.desktop
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: 'Exec=sakura', replace: 'Exec=sommelier -X sakura' }
