---

# Dotfiles

- name: Cloning dotfiles
  become_user: "{{ username }}"
  git: repo=https://github.com/palazzem/dotfiles.git dest="/home/{{username}}/.dotfiles" accept_hostkey=yes

- name: Removing old files (if any)
  file: state=absent name={{item}}
  with_items:
    - "/home/{{username}}/.zshrc"

- name: Creating symbolic links
  file: state=link src={{item.src}} dest={{item.dest}} owner={{username}} group={{username}}
  with_items:
      - { src: "/home/{{username}}/.dotfiles/zshrc", dest: "/home/{{username}}/.zshrc" }
