version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # Build the docker container that will be orchestrated with Hanzo.
      # For more details check: https://github.com/palazzem/hanzo/blob/master/Dockerfile#L21-L23
      - run: docker build -t hanzo:test .
