---

# System tasks that must run as a first role

- name: Update cache list
  pacman: update_cache=yes force=yes

- name: Preparing the base system
  pacman:
    state: latest
    name:
      - base
      - base-devel
      - linux
      - linux-headers

- name: Installing system packages
  pacman:
    state: latest
    name:
      - archey3
      - curl
      - dnsutils
      - dosfstools
      - fzf
      - git
      - htop
      - mlocate
      - mono
      - ntfsprogs
      - ntp
      - openssh
      - p7zip
      - sudo
      - tar
      - tree
      - unrar
      - unzip
      - wget
      - which
      - whois
      - zip
      - zsh

- name: Starting NTP daemon at boot time
  command: systemctl enable ntpd

- name: Adding default user
  user: name={{username}} groups=wheel append=yes

- name: Creating a default SSH key
  user: name={{username}} generate_ssh_key=yes ssh_key_bits=8192 ssh_key_passphrase={{ssh_password}}

- name: Creating 'programs' folder
  file: path="/home/{{username}}/programs" owner={{username}} group={{username}} state=directory

- name: Creating 'workspaces' folder
  file: path="/home/{{username}}/workspaces" owner={{username}} group={{username}} state=directory

- name: Adding 'wheel' group to sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) ALL'"
