---

# Ruby

- name: Installing system Ruby
  pacman:
    state: latest
    name: ruby

- name: Installing 'rbenv'
  aur:
    name:
      - rbenv
      - ruby-build
  become: yes
  become_user: aur_builder
