---

# Overview: configuring a developer machine in just minutes

- hosts: localhost
  tasks:
    - name: Configure the environment
      set_fact:
        email: "{{ lookup('env', 'EMAIL') | default(false, True) }}"
        fullname: "{{ lookup('env', 'FULLNAME') | default(false, True) }}"
        username: "{{ lookup('env', 'USERNAME') | default(false, True) }}"
        ssh_password: "{{ lookup('env', 'SSH_PASSWORD') | default(false, True) }}"
    - name: Checking required variables
      fail:
        msg: "Variable '{{item}}' is not defined."
      when: not vars[item]
      with_items:
        - email
        - fullname
        - ssh_password
        - username

- hosts: localhost
  become: yes
  vars_files:
    - variables/versions.yml
  tasks:
    - block:
        - include_role: name=system
        - include_role: name=aur
        - include_role: name=shell
        - include_role: name=development
        - include_role: name=editors
        - include_role: name=storages
        - include_role: name=orchestrators
        - include_role: name=provisioning
        - include_role: name=cluster
        - include_role: name=extras
        - include_role: name=fonts
        - include_role: name=dotfiles
      always:
        - include_role: name=cleanup
