---

# Overview: configuring a developer machine in just minutes

- hosts: localhost
  tasks:
    - name: Configure the environment
      set_fact:
        email: "{{ lookup('env', 'EMAIL') | default(false, True) }}"
        fullname: "{{ lookup('env', 'FULLNAME') | default(false, True) }}"
        username: "{{ lookup('env', 'USERNAME') | default(false, True) }}"
    - name: Checking required variables
      fail:
        msg: "Variable '{{item}}' is not defined."
      when: not vars[item]
      with_items:
        - email
        - fullname
        - username

- hosts: localhost
  become: yes
  vars_files:
    - variables/versions.yml
  roles:
    - system
    - shell
    - development
    - editors
    - storages
    - orchestrators
    - provisioning
    - cluster
    - extras
    - fonts
    - { role: dotfiles, tags: ['dotfiles'] }
