---

# Extras

- name: Installing consumer applications
  pacman:
    state: latest
    name:
      - gimp
      - imagemagick
      - libreoffice-en-US
      - libreoffice-fresh
      - mopidy
      - mpv
      - ncmpcpp
      - transmission-cli
      - youtube-dl
