---

# Docker

- name: Installing Docker
  pacman:
    state: latest
    name:
      - docker
      - docker-compose

- name: Adding default user to docker group
  user: name={{username}} groups=docker append=yes
