---

# ChromeOS dependencies so that UI applications can be used

- name: Installing Wayland
  pacman:
    state: latest
    name:
      - wayland
      - packagekit
      - xorg-server-xwayland

- name: Installing Containers Guest Tools
  aur:
    name: cros-container-guest-tools-git
  become: yes
  become_user: aur_builder

- name: Fixing xkeyboard-config 2.24 break the sommelier-x service
  replace:
    dest: /usr/share/X11/xkb/keycodes/evdev
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: '<I372>.*', replace: '// <I372> = 372;' }
    - { regexp: '<I374>.*', replace: '// <I374> = 374;' }

- name: Configure the container (config files)
  file: state=touch path={{item.path}} owner={{username}} group={{username}}
  with_items:
      - { path: "/home/{{username}}/.mime.types" }

- name: Configure the container (symlinks)
  file: state=link src={{item.src}} dest={{item.dest}}
  with_items:
      - { src: "/home/{{username}}/.dotfiles/config/mime.types", dest: "/etc/mime.types" }

# Sommelier is enabled via symlink because `systemctl` cannot be used
# when commands are executed directly on the LXC container, without
# a proper login. To make it work via `systemctl` it's required to
# access via `lxc console`.
- name: Creating 'default.target.wants' folder for systemd
  file: path="/home/{{username}}/.config/systemd/user/default.target.wants" owner={{username}} group={{username}} state=directory

- name: Enabling Sommelier via systemctl
  become: true
  become_user: "{{ username }}"
  file:
    state: link
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: '/usr/lib/systemd/user/sommelier@.service', dest: '/home/{{username}}/.config/systemd/user/default.target.wants/sommelier@0.service'}
    - { src: '/usr/lib/systemd/user/sommelier-x@.service', dest: '/home/{{username}}/.config/systemd/user/default.target.wants/sommelier-x@0.service'}
