---

# Fonts

- name: Installing community fonts
  pacman:
    state: latest
    name:
      - ttf-dejavu
      - adobe-source-code-pro-fonts
  notify:
    - build font cache

- name: Installing AUR fonts
  become: yes
  become_user: aur_builder
  aur:
    name:
      - ttf-symbola
      - artwiz-fonts
